###########
# General #
###########

# 0 - Trace
# 1 - Debug
# 2 - Info
# 4 - Warn
# 5 - Error
log_level: 2
threads: 10 # Number of threads to spin up

user_agents: 
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0"

##########
# Server #
##########

port: 8080 # port on which server should be launched
bind_ip: "0.0.0.0" # interface on the which server should listen on

rate_limiter: {
    number_of_requests: 20, # The number of request that are allowed within a provided time limit.
    time_limit: 3, # The time limit in which the quantity of requests that should be accepted.
  }
# timeout for the search requests sent to the upstream search engines to be fetched (value in seconds).
request_timeout: 30

##########
# Search #
##########

# 0 - No filtering
# 1 - Low ; Safe search level will be set to low on upstream engines
# 2 - Moderate ; Safe search level will be set to moderate on upstream engines
# 3 - High ; Safe search level will be set to high on upstream engines
safe_search_level: 1

### Search Engines ###
upstream_search_engines:
  Bing:
    enabled: true
    timeout: 10000
    score_multiplier: 1.0
  DuckDuckGo:
    enabled: true
    timeout: 7000
    score_multiplier: 1.0
# proxy:
#   connection_url: "socks5://127.0.0.1:9050"  # Example value for proxy
#   is_tor: true
#   proxy_type: Socks5
